export const asiaArray = [
    {
        id: 1,
        name: 'Bali',
        image: '/images-asia/bali.jpg',
        description: 'Where rice terraces meet powerful waterfalls. A true paradise where honesty and karma are culturally engraved.',
        area: '/asia/bali',
    },
    {
        id: 2,
        name: 'Vietnam',
        image: '/images-asia/vietnam.jpg',
        description: 'Vietnam is a country of contrasts, where loud, vibrant cities sit within touching distance of calm oceans and rising limestone karsts.',
        area: '/asia/vietnam',
    },
    {
        id: 3,
        name: 'India',
        image: '/images-asia/india.jpg',
        description: 'This is a place where women wash clothes together by the river, communities are loving, and families help each other collect coconuts from the trees. There is constant chatter, warm smiles, and the hand of friendship extended at every turn.',
        area: '/asia/india',
    },
    {
        id: 4,
        name: 'Indonesia',
        image: '/images-asia/indonesia.jpg',
        description: 'Mother nature really pulled out all the stops when it came to incredible Indonesia. A country made up of epic proportions and a generous serving of spectacular natural phenomena. All this, and more, make it a giant natural playground waiting to be explored!',
        area: '/asia/indonesia',
    },
    {
        id: 5,
        name: 'Laos',
        image: '/images-asia/laos.jpg',
        description: 'The wonderful feeling of peace and tranquility is unmistakable at every turn in beautiful Laos. In the stillness and magic of the misty green paddy fields, in the majestic nature of the forest-covered mountains, and in the spiritual silence of the barefoot monks as they walk together at dawn.',
        area: '/asia/laos',
    },
    {
        id: 6,
        name: 'Malaysia',
        image: '/images-asia/malaysia.jpg',
        description: 'The new and old exist side by side in diverse Malaysia! Witness cutting-edge designs, amongst heritage buildings and UNESCO protected sites, with some street art here and there.',
        area: '/asia/malaysia',
    },
    {
        id: 7,
        name: 'Maldives',
        image: '/images-asia/maldives.jpg',
        description: 'The Maldives is a desert island experience like no other. Be a small pin on a big map, and seize the once in a lifetime opportunity to travel to this remote oasis!',
        area: '/asia/maldives',
    },
    {
        id: 8,
        name: 'Myanmar',
        image: '/images-asia/myanmar.jpg',
        description: 'Myanmar: a little known nation, which at its core, is pure optimism and endless beauty. Part of its extensive beauty lies in the incredible sense of spirituality here. Discover this among the largest number of Buddhist temples in the world and their beautiful devotees.',
        area: '/asia/myanmar',
    },
    {
        id: 9,
        name: 'Philippines',
        image: '/images-asia/philippines.jpg',
        description: 'The Philippines is the second-largest archipelago in the world, with 7000+ islands. Azure waters that make the country a haven for island hoppers who want to experience everything the world’s biggest coconut producer has to offer!',
        area: '/asia/philippines',
    },
    {
        id: 10,
        name: 'Singapore',
        image: '/images-asia/singapore.jpg',
        description: 'One of the greatest cities in the world, Singapore is an ever-expanding cosmopolitan hub that is beautiful to visit in its own right, or as a base to explore Malaysia and other surrounding Asian countries. ',
        area: '/asia/singapore',
    },
    {
        id: 11,
        name: 'Sri Lanka',
        image: '/images-asia/sri-lanka.jpg',
        description: 'A myriad of cultures, religions, landscapes, climates, and food, Sri Lanka feels like countless countries rolled into one. Because of this, travelers can experience an incredible diversity in landscapes within a short space of time. ',
        area: '/asia/sri-lanka',
    },
    {
        id: 12,
        name: 'Thailand',
        image: '/images-asia/thailand.jpg',
        description: 'Thailand’s everlasting strength of spirit and known characterization as the ‘Land of Smiles’, has made it a timeless favorite amongst travelers worldwide.',
        area: '/asia/thailand',
    },
    
]

